name: 🚀 Publish Roadmap Badge to GitHub Pages

on:
  push:
    paths:
      - 'roadmap.md'
      - 'scripts/generate_roadmap_badge.py'

jobs:
  publish-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nécessaire pour manipuler plusieurs branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate badge
        run: python scripts/generate_roadmap_badge.py

      - name: Commit badge to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Sauvegarder badge
          cp roadmap.svg tmp_badge.svg

          # Passer sur gh-pages
          git checkout gh-pages

          # Copier et commit le badge
          mv tmp_badge.svg roadmap.svg
          git add roadmap.svg
          git commit -m "🔄 Update roadmap badge" || echo "No changes"
          git push origin gh-pages

          # Retour sur main
          git checkout main